version: "3.9"
services:
  database:
    container_name: bookstore-database
    image: mysql:8.0.32-debian
    user:
      "1000:1000"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: bookstore
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    logging:
      driver: none
    networks:
      - bookstore-network
  phpmyadmin:
    container_name: bookstore-phpmyadmin
    image: phpmyadmin:5.2.1-apache
    environment:
      PMA_HOST: database
      PMA_USER: admin
      PMA_PASSWORD: admin123
    links:
      - database
    logging:
      driver: none
    networks:
      - bookstore-network
  backend:
    container_name: bookstore-backend
    image: php:8.2.3-alpine3.17
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./backend/logs:/var/www/logs
    command: php -S 0.0.0.0:80 -t public
    links:
      - database
    environment:
      MYSQL_HOST: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: bookstore
    networks:
      - bookstore-network
  frontend:
    container_name: bookstore-frontend
    image: node:19-alpine3.16
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm start
    environment:
      - REACT_APP_BACKEND_URL=http://backend:80
      - PORT=80
    links:
      - backend
    networks:
      - bookstore-network
  nginx:
    container_name: bookstore-nginx
    image: nginx:1.23.3
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
    links:
      - backend
      - frontend
      - phpmyadmin
    networks:
      - bookstore-network
networks:
  bookstore-network:
    driver: bridge
