version: "3"
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    # links:
    #   - frontend
    #   - backend
  react:
    build: ./frontend
    ports:
      - 3000:3000
  # php:
  #   build: ./backend
  #   ports:
  #     - 9000:9000
  #   links:
  #     - mysql
  database:
    build: ./database
    ports:
      - "3306:3306"
